# Generated by Django 6.0 on 2025-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
            ],
        ),
    ]
